# Generated by Django 2.1.5 on 2019-01-22 17:42

import sectacms.blocks.base_blocks
import sectacms.fields
from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sectacms', '0007_auto_20190114_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentwall',
            name='content',
            field=sectacms.fields.sectaStreamField([], blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='content',
            field=sectacms.fields.sectaStreamField([], blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='reusablecontent',
            name='content',
            field=sectacms.fields.sectaStreamField([], blank=True, verbose_name='content'),
        ),
    ]
